In [1]:
lst = []
print("Enter 5 names : ")
for i in range(0, 5):
    ele = input()
    lst.append(ele)
    lst.sort()
print("The sorted array is :", lst)

Enter 5 names : 
Ram
Shyam
Ravan
Sita
Laxman
The sorted array is : ['Laxman', 'Ram', 'Ravan', 'Shyam', 'Sita']


In [14]:
sample_list = [6, 98, 34, 45, 64, 7, 2, 5, 78, 90, 324, 111, 657, 438]
factors = {}

def print_factors(x):
    for i in range(1, x + 1):
        if x % i == 0:
            l.append(i) 
    return l

for j in range(0, len(sample_list)):
    l = []
    m = print_factors(sample_list[j])
    factors[sample_list[j]] = m
factors

{6: [1, 2, 3, 6],
 98: [1, 2, 7, 14, 49, 98],
 34: [1, 2, 17, 34],
 45: [1, 3, 5, 9, 15, 45],
 64: [1, 2, 4, 8, 16, 32, 64],
 7: [1, 7],
 2: [1, 2],
 5: [1, 5],
 78: [1, 2, 3, 6, 13, 26, 39, 78],
 90: [1, 2, 3, 5, 6, 9, 10, 15, 18, 30, 45, 90],
 324: [1, 2, 3, 4, 6, 9, 12, 18, 27, 36, 54, 81, 108, 162, 324],
 111: [1, 3, 37, 111],
 657: [1, 3, 9, 73, 219, 657],
 438: [1, 2, 3, 6, 73, 146, 219, 438]}

In [31]:
l=[]
string = input("Enter your string : ")
for i in range(0, len(string)):
    if string[i] not in ('aeiouAEIOU'):
         l.append(string[i])
print(l)
if(x not in ('aeiouAEIOU'))

Enter your string : orb
['r', 'b']


In [45]:
from functools import reduce
string=[]
string = input("Enter your string : ")
l = reduce((lambda x,y : x if(x not in ('aeiouAEIOU')) else y), string)
l

Enter your string : ornate


'r'

In [1]:
import csv
  
# field names
fields = ['Name', 'Branch', 'Year', 'CGPA']
  
# data rows of csv file
rows = [ ['Nikhil', 'COE', '2', '9.0'],
         ['Sanchit', 'COE', '2', '9.1'],
         ['Aditya', 'IT', '2', '9.3'],
         ['Sagar', 'SE', '1', '9.5'],
         ['Prateek', 'MCE', '3', '7.8'],
         ['Sahil', 'EP', '2', '9.1']]
  
# name of csv file
filename = "university_records.csv"
  
# writing to csv file
with open(filename, 'w') as csvfile:
    # creating a csv writer object
    csvwriter = csv.writer(csvfile)
      
    # writing the fields
    csvwriter.writerow(fields)
      
    # writing the data rows
    csvwriter.writerows(rows)

In [9]:
filename = "university_records.csv"
fields = []
rows = []
with open(filename, 'r') as csvfile:
    # creating a csv reader object
    csvreader = csv.reader(csvfile)
      
    # extracting field names through first row
    fields = next(csvreader)
  
    # extracting each data row one by one
    for row in csvreader:
        rows.append(row)
  
    # get total number of rows
    print("Total no. of rows: %d"%(csvreader.line_num))
  
# printing the field names
print('Field names are:' + ', '.join(field for field in fields))
  
#  printing first 5 rows
print('\nFirst 5 rows are:\n')
for row in rows[:]:
    # parsing each column of a row
    for col in row:
        print("%10s"%col),
    print('\n')

Total no. of rows: 14
Field names are:Name, Branch, Year, CGPA

First 5 rows are:



    Nikhil
       COE
         2
       9.0




   Sanchit
       COE
         2
       9.1




    Aditya
        IT
         2
       9.3




     Sagar
        SE
         1
       9.5




   Prateek
       MCE
         3
       7.8




     Sahil
        EP
         2
       9.1






In [42]:
import numpy as np
input_list = [[[7, 13, 14], [18, 10, 17], [11, 12, 19]], [16, 6, 1], [[5, 8, 4, 3]]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]
print(list_1, '\n', list_2,'\n',list_3)

[[7, 13, 14], [18, 10, 17], [11, 12, 19]] 
 [16, 6, 1] 
 [[5, 8, 4, 3]]


In [98]:
final_array = np.hstack((final_array,np.reshape(list_3, (1,4))))
#np.concatenate((list_1, np.array(list_2)), axis=1)
#np.shape(list_3)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

In [68]:
list_2 = np.reshape(list_2, (1,3))

In [59]:
final_array

array([[ 7, 13, 14, 16],
       [18, 10, 17,  6],
       [11, 12, 19,  1]])

In [39]:
np.reshape(list_2, (1,3))

array([[16,  6,  1]])

In [106]:
list_3 = np.array(list_3)
list_3 = np.reshape(list_3, (4,1))
list_3

array([[5],
       [8],
       [4],
       [3]])

In [107]:
final_array = np.append(final_array,list_3, axis=1)

In [108]:
final_array

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [109]:
import numpy as np
list_1 = np.array(list_1)
list_2 = np.array(list_2)
list_2 = np.reshape(list_2, (1,3))
list_3 = np.array(list_3)
list_3 = np.reshape(list_3, (4,1))
list_3
# Write your code here
final_array = np.append(list_1,list_2, axis=0)
final_array = np.append(final_array,list_3, axis=1)
print(final_array)

[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [110]:
import pandas
pandas.__version__

'1.3.4'

In [111]:
import webbrowser

webbrowser.open('http://google.com') 

True

In [112]:
import urllib

fun open():
    return urllib.urlopen('http://google.com')

SyntaxError: invalid syntax (Temp/ipykernel_10536/2666634490.py, line 3)

In [113]:
y = np.empty(5)

In [117]:
y = x * 10
y

array([ 0, 10, 20, 30, 40])

In [116]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [118]:
np.multiply(x,12,out=y)

array([ 0, 12, 24, 36, 48])

In [119]:
y = np.zeros(10)

In [120]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [122]:
np.power(2,x,out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [123]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [124]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [125]:
np.add.reduce(x)

15

In [126]:
sum(x)

15

In [128]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [129]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [130]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [131]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [133]:
np.linalg.matrix_rank(A)

3

In [134]:
np.trace(A)

11

In [135]:
np.linalg.det(A)

-306.0

In [138]:
B = np.linalg.inv(A)
B

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [139]:
np.matmul(A,B)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 2.22044605e-16, 1.00000000e+00]])

In [140]:
np.linalg.matrix_power(A,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [141]:
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

In [2]:
import time

In [148]:
t0 = time.time()
product_list = list(map(lambda x, y : x * y, list_1, list_2))
t1 = time.time()
list_time = t1 -t0
print(list_time)

0.09656786918640137


In [146]:
array_1 = np.array(list_1)
array_2 = np.array(list_2)

In [149]:
t0 = time.time()
product_list = array_1 * array_2
t1 = time.time()
numpy_time = t1 -t0
print(numpy_time)

0.011554241180419922


In [4]:
import time
import numpy as np

list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

t0 = time.time()
product_list = list(map(lambda x, y : x * y, list_1, list_2))
t1 = time.time()
list_time = t1 -t0
print(list_time)

array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
product_list = array_1 * array_2
t1 = time.time()
numpy_time = t1 -t0
print(numpy_time)

print("The ratio of time taken is : ",format(list_time//numpy_time))

0.08955764770507812
0.010971307754516602
The ratio of time taken is :  8.0
